# Generated by Django 3.1.3 on 2021-08-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('github', models.URLField()),
                ('demo', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Project Info',
                'verbose_name_plural': 'Projects Info',
            },
        ),
    ]
